/**
 * E2E: the quality of every secret the library hands out, against REAL Postgres
 * and REAL Redis.
 *
 * Sourced from OWASP ASVS V7 (session tokens carry at least 64 bits of entropy, a
 * new token is issued on authentication, tokens never travel in URL parameters,
 * a user can enumerate and revoke their own sessions) and the OWASP Forgot
 * Password and Authentication cheat sheets (reset tokens generated by a
 * cryptographic RNG, long enough to resist brute force, time limited, and
 * responses that do not vary by whether an account exists).
 *
 * Guessability is the one property that cannot be inferred from reading the code:
 * `randomToken(32)` looks right in a diff whatever it returns. These cases sample
 * the real output instead.
 *
 * Findings are recorded, not repaired.
 *
 * Skips when DUCKAUTH_E2E_DATABASE_URL or DUCKAUTH_E2E_REDIS_URL is unset;
 * `globalSetup` provisions both when docker is available.
 */
import Redis from 'ioredis'
import { Pool } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { drizzlePgStorage } from '~/adapters/drizzle/pg'
import { AuthTestChannel } from '~/channels/console'
import { randomToken, sha256 } from '~/core/crypto'
import { AuthEngine } from '~/core/engine'
import { InMemoryEvents } from '~/core/events'
import { CookieTransport } from '~/core/transport/cookie.transport'
import { RedisLimiter } from '~/limiters/redis'
import { ApiKeysFacet } from '~/providers/api-key'
import { mfaProvider } from '~/providers/mfa'
import { passwords, ScryptHasher } from '~/providers/passwords'
import { applyPgSchema, databaseUrl, dropPrefix, e2ePrefix, redisUrl } from '~/test/e2e-env'
import { toRedisLike } from '~/test/e2e-redis'

const PG_URL = databaseUrl()
const REDIS_URL = redisUrl()
const suite = PG_URL && REDIS_URL ? describe : describe.skip

type Profile = { username: string; email: string }
const PASSWORD = 'correct-horse-battery'

/** base64url with no padding: the only shape any of these secrets should take. */
const BASE64URL = /^[A-Za-z0-9_-]+$/

/**
 * Shannon entropy per character, in bits. A cryptographic RNG rendered in
 * base64url approaches 6; anything markedly below it means the alphabet is not
 * being used evenly, which is what a broken RNG looks like from outside.
 */
function bitsPerChar(samples: string[]): number {
  const counts = new Map<string, number>()
  let total = 0
  for (const s of samples) {
    for (const ch of s) {
      counts.set(ch, (counts.get(ch) ?? 0) + 1)
      total += 1
    }
  }
  let bits = 0
  for (const n of counts.values()) {
    const p = n / total
    bits -= p * Math.log2(p)
  }
  return bits
}

suite('E2E token quality on real Postgres + Redis', () => {
  let pool: Pool
  let raw: Redis
  let prefix: string
  let auth: AuthEngine<Profile>
  let stores: ReturnType<typeof drizzlePgStorage<Profile>>
  let keys: ApiKeysFacet
  const planted: string[] = []

  async function newUser(label: string): Promise<{ id: string; email: string }> {
    const tag = `${label}-${e2ePrefix()}`
    const email = `${tag}@test.local`
    const identity = await auth.identities.create({ profile: { email, username: tag } })
    await auth.passwords.set(identity.id, PASSWORD, stores.credentials)
    planted.push(identity.id)
    return { email, id: identity.id }
  }

  async function resetToken(email: string, channel = new AuthTestChannel()): Promise<string> {
    await auth.flows.requestPasswordReset({
      channels: { email: channel },
      findIdentityByEmail: async (e) => stores.identities.findByEmail(e),
      input: { email },
    })
    const entry = channel.outbox.at(-1)
    const url = (entry?.vars as { url?: string } | undefined)?.url
    return new URL(url as string).searchParams.get('token') as string
  }

  beforeAll(async () => {
    pool = new Pool({ connectionString: PG_URL })
    await applyPgSchema(pool)
    raw = new Redis(REDIS_URL as string, { lazyConnect: true, maxRetriesPerRequest: 2 })
    await raw.connect()
    prefix = e2ePrefix()
    stores = drizzlePgStorage<Profile>(PG_URL as string)
    auth = new AuthEngine<Profile>({
      baseUrl: 'https://app.test',
      limiter: new RedisLimiter({ max: 2000, prefix, redis: toRedisLike(raw), windowMs: 60_000 }),
      stores: { credentials: stores.credentials, identities: stores.identities, sessions: stores.sessions },
      transport: new CookieTransport({ name: 'duck-sid', secure: false }),
    })
    auth.providers.register(passwords<Profile>({ hasher: new ScryptHasher({ keylen: 32, N: 1 << 10 }) }))
    const m = mfaProvider()
    auth.providers.register(typeof m === 'function' ? m(auth as never) : m)
    keys = new ApiKeysFacet(stores.credentials, new InMemoryEvents(), { randomToken, sha256 })
  }, 60_000)

  afterAll(async () => {
    if (raw) {
      await dropPrefix(raw, prefix)
      await raw.quit()
    }
    if (pool && planted.length > 0) {
      await pool.query('DELETE FROM auth_identities WHERE id = ANY($1::uuid[])', [planted])
    }
    await pool?.end()
  })

  describe('session identifiers', () => {
    it('carries far more than the sixty-four bits ASVS asks for', async () => {
      const { sid } = await auth.sessions.createGuest()
      expect(sid).toMatch(BASE64URL)
      // 43 base64url characters is 32 bytes, so 256 bits.
      expect(sid.length).toBeGreaterThanOrEqual(22)
      expect(sid.length * 6).toBeGreaterThanOrEqual(64)
    })

    it('never repeats across two thousand issues', async () => {
      const sids = await Promise.all(Array.from({ length: 2000 }, () => auth.sessions.createGuest()))
      expect(new Set(sids.map((s) => s.sid)).size).toBe(2000)
    })

    it('spreads evenly over the alphabet', async () => {
      const sids = await Promise.all(Array.from({ length: 300 }, () => auth.sessions.createGuest()))
      // Near 6 bits per character for base64url. A counter, a timestamp or a
      // seeded PRNG would sit visibly below this.
      expect(bitsPerChar(sids.map((s) => s.sid))).toBeGreaterThan(5.8)
    })

    it('shares no prefix between consecutive issues', async () => {
      // A time-seeded generator leaks its clock into a common leading run.
      const a = await auth.sessions.createGuest()
      const b = await auth.sessions.createGuest()
      expect(a.sid.slice(0, 8)).not.toBe(b.sid.slice(0, 8))
    })

    it('stores only the hash, so the row never carries the plaintext', async () => {
      const { session, sid } = await auth.sessions.createGuest()
      expect(session.id).toBe(sha256(sid))
      expect(session.id).not.toBe(sid)
      const { rows } = await pool.query('SELECT count(*)::int AS n FROM auth_sessions WHERE id = $1', [sid])
      expect(rows[0].n).toBe(0)
    })

    it('is issued fresh on authentication, never carried over', async () => {
      const user = await newUser('sid-fresh')
      const guest = await auth.sessions.createGuest()
      const signedIn = await auth.flows.signIn({
        input: { email: user.email, password: PASSWORD },
        previousSid: guest.sid,
        providerId: 'password',
      })
      expect(signedIn.sid).not.toBe(guest.sid)
    })

    it('travels on a cookie, never in a URL', async () => {
      // ASVS V7: a token in a query string ends up in referrer headers, proxy logs
      // and browser history.
      const user = await newUser('sid-url')
      const { intents } = await auth.flows.signIn({
        input: { email: user.email, password: PASSWORD },
        providerId: 'password',
      })
      for (const intent of intents) {
        if (intent.type === 'redirect') expect(intent.url).not.toContain('duck-sid')
      }
      expect(intents.some((i) => i.type === 'setCookie' && i.name === 'duck-sid')).toBe(true)
    })
  })

  describe('CSRF tokens', () => {
    it('are unique across a thousand sessions', async () => {
      const made = await Promise.all(Array.from({ length: 1000 }, () => auth.sessions.createGuest()))
      expect(new Set(made.map((m) => m.csrfToken)).size).toBe(1000)
    })

    it('are unrelated to the session id they accompany', async () => {
      const { csrfToken, session, sid } = await auth.sessions.createGuest()
      expect(csrfToken).not.toBe(sid)
      expect(csrfToken).not.toBe(session.id)
      expect(session.csrfHash).toBe(sha256(csrfToken))
    })

    it('spread evenly over the alphabet', async () => {
      const made = await Promise.all(Array.from({ length: 300 }, () => auth.sessions.createGuest()))
      expect(bitsPerChar(made.map((m) => m.csrfToken))).toBeGreaterThan(5.8)
    })
  })

  describe('API keys', () => {
    it('carry a recognisable prefix and enough randomness after it', async () => {
      const id = await newUser('key-entropy')
      const { plaintext } = await keys.create(id.id, { name: 'ci', scopes: ['read'] })
      const random = plaintext.replace(/^[a-z_]+/, '')
      expect(random.length * 6).toBeGreaterThanOrEqual(64)
    })

    it('never repeat across five hundred issues', async () => {
      const id = await newUser('key-unique')
      const made = await Promise.all(
        Array.from({ length: 500 }, () => keys.create(id.id, { name: 'ci', scopes: ['read'] })),
      )
      expect(new Set(made.map((m) => m.plaintext)).size).toBe(500)
    })

    it('are stored hashed, so the table never holds the secret', async () => {
      const id = await newUser('key-hashed')
      const { plaintext } = await keys.create(id.id, { name: 'ci', scopes: ['read'] })
      const { rows } = await pool.query('SELECT count(*)::int AS n FROM auth_credentials WHERE secret = $1', [
        plaintext,
      ])
      expect(rows[0].n).toBe(0)
    })
  })

  describe('password reset tokens', () => {
    it('are long enough to resist brute force', async () => {
      const user = await newUser('reset-entropy')
      const token = await resetToken(user.email)
      expect(token).toMatch(BASE64URL)
      expect(token.length * 6).toBeGreaterThanOrEqual(64)
    })

    it('never repeat across a hundred requests', async () => {
      const user = await newUser('reset-unique')
      const channel = new AuthTestChannel()
      const tokens: string[] = []
      for (let i = 0; i < 100; i++) tokens.push(await resetToken(user.email, channel))
      expect(new Set(tokens).size).toBe(100)
    })

    it('spread evenly over the alphabet', async () => {
      const user = await newUser('reset-spread')
      const channel = new AuthTestChannel()
      const tokens: string[] = []
      for (let i = 0; i < 120; i++) tokens.push(await resetToken(user.email, channel))
      expect(bitsPerChar(tokens)).toBeGreaterThan(5.8)
    })

    it('are stored hashed, so the table never holds the token', async () => {
      const user = await newUser('reset-hashed')
      const token = await resetToken(user.email)
      const { rows } = await pool.query('SELECT count(*)::int AS n FROM auth_credentials WHERE secret = $1', [token])
      expect(rows[0].n).toBe(0)
    })

    it('FINDING: issuing a new reset token leaves every earlier one live', async () => {
      // Ten requests, ten working keys to the account, sitting in ten inboxes.
      // Each is single use and time limited, so this is not unbounded, but the
      // usual expectation is that a fresh request retires the ones before it: an
      // old message forwarded, archived or leaked should stop being a way in.
      const user = await newUser('reset-accumulate')
      const channel = new AuthTestChannel()
      const tokens: string[] = []
      for (let i = 0; i < 10; i++) tokens.push(await resetToken(user.email, channel))

      // The first token, issued before nine others, still resets the password.
      await expect(
        auth.flows.completePasswordReset({ newPassword: 'a-brand-new-password', token: tokens[0] as string }),
      ).resolves.toEqual({ ok: true })
    })

    it('is rate limited per address, so it cannot be used to send mail forever', async () => {
      const limited = new AuthEngine<Profile>({
        baseUrl: 'https://app.test',
        limiter: new RedisLimiter({ max: 3, prefix: `${prefix}:rl`, redis: toRedisLike(raw), windowMs: 60_000 }),
        stores: { credentials: stores.credentials, identities: stores.identities, sessions: stores.sessions },
        transport: new CookieTransport({ name: 'duck-sid', secure: false }),
      })
      limited.providers.register(passwords<Profile>({ hasher: new ScryptHasher({ keylen: 32, N: 1 << 10 }) }))
      const m = mfaProvider()
      limited.providers.register(typeof m === 'function' ? m(limited as never) : m)

      const user = await newUser('reset-rl')
      const channel = new AuthTestChannel()
      for (let i = 0; i < 10; i++) {
        await limited.flows
          .requestPasswordReset({
            channels: { email: channel },
            findIdentityByEmail: async (e) => stores.identities.findByEmail(e),
            input: { email: user.email },
          })
          .catch(() => undefined)
      }
      expect(channel.outbox.length).toBeLessThan(10)
    })
  })

  describe('responses that must not reveal whether an account exists', () => {
    it('answers a reset for an unknown address exactly as for a known one', async () => {
      const user = await newUser('enum-known')
      const knownChannel = new AuthTestChannel()
      const unknownChannel = new AuthTestChannel()

      const known = await auth.flows.requestPasswordReset({
        channels: { email: knownChannel },
        findIdentityByEmail: async (e) => stores.identities.findByEmail(e),
        input: { email: user.email },
      })
      const unknown = await auth.flows.requestPasswordReset({
        channels: { email: unknownChannel },
        findIdentityByEmail: async (e) => stores.identities.findByEmail(e),
        input: { email: `ghost-${e2ePrefix()}@test.local` },
      })

      expect(known).toEqual(unknown)
      expect(unknownChannel.outbox).toHaveLength(0)
    })

    it('takes a comparable amount of time for a known and an unknown account', async () => {
      // A quick exit on "no such user" is an enumeration oracle. Sampled rather
      // than measured precisely, with a wide band, because a tight timing bound in
      // a test suite is a flake generator.
      const user = await newUser('enum-timing')
      const attempt = async (email: string) => {
        const started = performance.now()
        await auth.flows
          .signIn({ input: { email, password: 'definitely-wrong' }, providerId: 'password' })
          .catch(() => undefined)
        return performance.now() - started
      }

      let known = 0
      let unknown = 0
      for (let i = 0; i < 25; i++) {
        known += await attempt(user.email)
        unknown += await attempt(`ghost-${e2ePrefix()}@test.local`)
      }
      const ratio = known / unknown
      expect(ratio).toBeGreaterThan(0.2)
      expect(ratio).toBeLessThan(5)
    })
  })

  describe('a user can see and end their own sessions', () => {
    it('lists every live session and nothing belonging to anyone else', async () => {
      const mine = await newUser('list-mine')
      const theirs = await newUser('list-theirs')
      await auth.flows.signIn({ input: { email: mine.email, password: PASSWORD }, providerId: 'password' })
      await auth.flows.signIn({ input: { email: mine.email, password: PASSWORD }, providerId: 'password' })
      await auth.flows.signIn({ input: { email: theirs.email, password: PASSWORD }, providerId: 'password' })

      const listed = await auth.sessions.listForIdentity(mine.id)
      expect(listed).toHaveLength(2)
      expect(listed.every((s) => s.identityId === mine.id)).toBe(true)
    })

    it('the listing carries no secret that could reconstruct a session', async () => {
      const user = await newUser('list-secret')
      const { sid } = await auth.flows.signIn({
        input: { email: user.email, password: PASSWORD },
        providerId: 'password',
      })
      const listed = await auth.sessions.listForIdentity(user.id)
      expect(JSON.stringify(listed)).not.toContain(sid)
    })

    it('ending them all leaves nothing resolvable', async () => {
      const user = await newUser('list-revoke')
      const a = await auth.flows.signIn({ input: { email: user.email, password: PASSWORD }, providerId: 'password' })
      const b = await auth.flows.signIn({ input: { email: user.email, password: PASSWORD }, providerId: 'password' })

      await auth.sessions.revokeAllForIdentity(user.id)

      for (const sid of [a.sid, b.sid]) {
        expect(await auth.resolveSession({ headers: new Headers({ cookie: `duck-sid=${sid}` }) })).toBeNull()
      }
      expect(await auth.sessions.listForIdentity(user.id)).toHaveLength(0)
    })
  })
})
