import { baseExternal, createTsdownConfig } from '@gentleduck/tsdown-config'

export default createTsdownConfig({
  entry: {
    index: 'src/index.ts',
    'core/index': 'src/core/index.ts',
    'core/transport/index': 'src/core/transport/index.ts',
    'core/errors': 'src/core/errors.ts',
    'adapters/memory/index': 'src/adapters/memory/index.ts',
    'adapters/redis/index': 'src/adapters/redis/index.ts',
    'adapters/sql/index': 'src/adapters/sql/index.ts',
    'channels/console/index': 'src/channels/console/index.ts',
    'channels/smtp/index': 'src/channels/smtp/index.ts',
    'channels/resend/index': 'src/channels/resend/index.ts',
    'channels/twilio/index': 'src/channels/twilio/index.ts',
    'channels/webpush/index': 'src/channels/webpush/index.ts',
    'limiters/memory/index': 'src/limiters/memory/index.ts',
    'providers/password/index': 'src/providers/password/index.ts',
    'providers/magic-link/index': 'src/providers/magic-link/index.ts',
    'providers/oauth/google/index': 'src/providers/oauth/google/index.ts',
    'providers/oauth/github/index': 'src/providers/oauth/github/index.ts',
    'providers/passkey/index': 'src/providers/passkey/index.ts',
    'providers/api-key/index': 'src/providers/api-key/index.ts',
    'server/generic/index': 'src/server/generic/index.ts',
    'server/express/index': 'src/server/express/index.ts',
    'server/hono/index': 'src/server/hono/index.ts',
    'server/next/index': 'src/server/next/index.ts',
    'client/vanilla/index': 'src/client/vanilla/index.ts',
    'client/react/index': 'src/client/react/index.ts',
    'cli/index': 'src/cli/index.ts',
    'openapi/index': 'src/openapi/index.ts',
    'telemetry/otel/index': 'src/telemetry/otel/index.ts',
  },
  external: [...baseExternal, 'react'],
})
