import { baseExternal, createTsdownConfig } from '@gentleduck/tsdown-config'

export default createTsdownConfig({
  entry: {
    index: 'src/index.ts',
    'core/index': 'src/core/index.ts',
    'core/transport/index': 'src/core/transport/index.ts',
    'core/dataAtRest/index': 'src/core/dataAtRest/index.ts',
    'core/errors': 'src/core/errors/index.ts',
    'adapters/memory/index': 'src/adapters/memory/index.ts',
    'adapters/redis/index': 'src/adapters/redis/index.ts',
    'adapters/sql/index': 'src/adapters/sql/index.ts',
    'adapters/drizzle/pg/index': 'src/adapters/drizzle/pg/index.ts',
    'adapters/drizzle/mysql/index': 'src/adapters/drizzle/mysql/index.ts',
    'adapters/drizzle/sqlite/index': 'src/adapters/drizzle/sqlite/index.ts',
    'channels/console/index': 'src/channels/console/index.ts',
    'channels/smtp/index': 'src/channels/smtp/index.ts',
    'channels/resend/index': 'src/channels/resend/index.ts',
    'channels/twilio/index': 'src/channels/twilio/index.ts',
    'channels/webpush/index': 'src/channels/webpush/index.ts',
    'channels/ses/index': 'src/channels/ses/index.ts',
    'limiters/memory/index': 'src/limiters/memory/index.ts',
    'providers/passwords/index': 'src/providers/passwords/index.ts',
    'providers/mfa/index': 'src/providers/mfa/index.ts',
    'providers/magic-link/index': 'src/providers/magic-link/index.ts',
    'providers/oauth/google/index': 'src/providers/oauth/google/index.ts',
    'providers/oauth/github/index': 'src/providers/oauth/github/index.ts',
    'providers/oauth/linkedin/index': 'src/providers/oauth/linkedin/index.ts',
    'providers/oauth/microsoft/index': 'src/providers/oauth/microsoft/index.ts',
    'providers/oauth/discord/index': 'src/providers/oauth/discord/index.ts',
    'providers/oauth/apple/index': 'src/providers/oauth/apple/index.ts',
    'providers/passkey/index': 'src/providers/passkey/index.ts',
    'providers/api-key/index': 'src/providers/api-key/index.ts',
    'providers/saml/index': 'src/providers/saml/index.ts',
    'server/generic/index': 'src/server/generic/index.ts',
    'server/express/index': 'src/server/express/index.ts',
    'server/hono/index': 'src/server/hono/index.ts',
    'server/next/index': 'src/server/next/index.ts',
    'server/fastify/index': 'src/server/fastify/index.ts',
    'server/koa/index': 'src/server/koa/index.ts',
    'server/elysia/index': 'src/server/elysia/index.ts',
    'server/nestjs/index': 'src/server/nestjs/index.ts',
    'server/grpc/index': 'src/server/grpc/index.ts',
    'client/vanilla/index': 'src/client/vanilla/index.ts',
    'client/react/index': 'src/client/react/index.ts',
    'client/react/storybook/index': 'src/client/react/storybook/index.ts',
    'client/vue/index': 'src/client/vue/index.ts',
    'client/svelte/index': 'src/client/svelte/index.ts',
    'client/solid/index': 'src/client/solid/index.ts',
    'cli/index': 'src/cli/index.ts',
    'openapi/index': 'src/openapi/index.ts',
    'oidc/index': 'src/oidc/index.ts',
    'oidc/op/index': 'src/oidc/op/index.ts',
    'oidc/op/drizzle/pg': 'src/oidc/op/drizzle/pg.ts',
    'oidc/op/drizzle/sqlite': 'src/oidc/op/drizzle/sqlite.ts',
    'oidc/op/drizzle/mysql': 'src/oidc/op/drizzle/mysql.ts',
    'i18n/index': 'src/i18n/index.ts',
    'telemetry/otel/index': 'src/telemetry/otel/index.ts',
    'test/index': 'src/test/index.ts',
  },
  external: [...baseExternal, 'react'],
})
