import { readFileSync } from 'node:fs'
import { glob } from 'node:fs/promises'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * `docs/TEST-INVENTORY.md` is generated by `scripts/gen-test-inventory.ts`. It
 * used to carry "This is a snapshot, not generated - update it by hand", and it
 * drifted from 93 files to 189: 96 test files missing, and the missing ones
 * were the round-1 security-fix tests. The inventory was least accurate about
 * exactly the tests that mattered most.
 *
 * The generator runs the whole suite, so it cannot run from inside the suite.
 * These tests check the cheap invariants instead - that every test file on disk
 * appears, that the stated totals match the row counts, and that the file still
 * declares itself generated - which is what actually rots. `--check` in the
 * generator covers byte-for-byte staleness for CI.
 */

const PKG = join(import.meta.dirname, '../..')
const INVENTORY = readFileSync(join(PKG, 'docs/TEST-INVENTORY.md'), 'utf8')

async function testFilesOnDisk(): Promise<string[]> {
  const out: string[] = []
  for await (const f of glob('**/*.test.ts?(x)', { cwd: join(PKG, 'src') })) out.push(f)
  return out.sort()
}

/** `| \`path\` | 12 | … |` rows, excluding the **Subtotal** / **Total** rows. */
function inventoryRows(): { file: string; tests: number }[] {
  const rows: { file: string; tests: number }[] = []
  for (const m of INVENTORY.matchAll(/^\| `([^`]+)` \| (\d+) \|/gm)) {
    const file = m[1]
    const tests = m[2]
    if (file === undefined || tests === undefined) continue
    rows.push({ file, tests: Number(tests) })
  }
  return rows
}

describe('test inventory stays honest', () => {
  it('lists every test file that exists on disk', async () => {
    const disk = await testFilesOnDisk()
    const listed = new Set(inventoryRows().map((r) => r.file))
    expect(disk.filter((f) => !listed.has(f))).toEqual([])
  })

  it('lists no test file that does not exist', async () => {
    const disk = new Set(await testFilesOnDisk())
    expect(
      inventoryRows()
        .map((r) => r.file)
        .filter((f) => !disk.has(f)),
    ).toEqual([])
  })

  it('the stated total matches the sum of its own rows', () => {
    const rows = inventoryRows()
    const m = /\| \*\*Total\*\* \| \*\*(\d+)\*\* \| \*\*(\d+)\*\* \|/.exec(INVENTORY)
    expect(m).not.toBeNull()
    expect(Number(m?.[1])).toBe(rows.length)
    expect(Number(m?.[2])).toBe(rows.reduce((n, r) => n + r.tests, 0))
  })

  it('still declares itself generated', () => {
    // The previous version's "update this file by hand" instruction is the
    // mechanism that produced the drift; it must not come back.
    expect(INVENTORY).toContain('This file is generated')
    expect(INVENTORY).not.toContain('not generated')
    expect(INVENTORY).toContain('bun run gen:test-inventory')
  })

  it('the row parser is not silently matching nothing', () => {
    expect(inventoryRows().length).toBeGreaterThan(100)
  })
})
