/**
 * NOTE THIS WHOLE FILE IS NOT REVIEWED NEITHER TRUST BY ME THE @author wildduck2
 * it's generated by AI.
 */
export namespace RedisLike {
  /**
   * Minimal Redis interface the auth adapters consume, shaped after `@upstash/redis`.
   * `ioredis`/`iovalkey` take `set` options variadically instead, so passing one
   * straight through silently drops every TTL and NX guard; wrap those with
   * `adapters/valkey` first.
   */
  export type Client = {
    /** GET key -> value | null */
    get(key: string): Promise<string | null>
    /** SET key value [EX seconds] [NX] -> 'OK' | null (null = NX failed) */
    set(key: string, value: string, opts?: { ex?: number; nx?: boolean }): Promise<'OK' | null>
    /** DEL key... -> count */
    del(...keys: string[]): Promise<number>
    /** EXPIRE key seconds -> 1 | 0 */
    expire(key: string, seconds: number): Promise<number>
    /** SCAN cursor MATCH pattern COUNT n -> [nextCursor, keys] */
    scan(cursor: string, opts?: { match?: string; count?: number }): Promise<[string, string[]]>
    /** INCR key -> new value (creates key=1 if missing) */
    incr(key: string): Promise<number>
    /** SADD key member... -> added count */
    sadd(key: string, ...members: string[]): Promise<number>
    /** SREM key member... -> removed count */
    srem(key: string, ...members: string[]): Promise<number>
    /** SMEMBERS key -> array of members (empty when key missing) */
    smembers(key: string): Promise<string[]>
    /** ZADD key score member -> 1 when added, 0 when an existing member was re-scored */
    zadd(key: string, score: number, member: string): Promise<number>
    /** ZREM key member... -> removed count */
    zrem(key: string, ...members: string[]): Promise<number>
    /**
     * ZRANGEBYSCORE key min max [LIMIT offset count] -> members in score order.
     * `min`/`max` accept `'-inf'` and `'+inf'`, and are inclusive.
     */
    zrangebyscore(
      key: string,
      min: number | string,
      max: number | string,
      opts?: { limit?: { offset: number; count: number } },
    ): Promise<string[]>
    /** EVAL script numKeys keys... args... -> result */
    eval?(script: string, opts: { keys: string[]; args: string[] }): Promise<unknown>
  }
}

/** `'-inf'` / `'+inf'` / a numeric bound -> a number, falling back for anything else. */
function bound(v: number | string, fallback: number): number {
  if (typeof v === 'number') return v
  const parsed = Number(v)
  return Number.isNaN(parsed) ? fallback : parsed
}

/**
 * In-process Redis substitute. Used by tests and by apps that need the
 * adapter shape without a real Redis dependency at runtime. Same surface
 * as ioredis / upstash; TTLs honored via setTimeout cleanup on read.
 */
export class FakeRedis implements RedisLike.Client {
  private readonly _data = new Map<string, { value: string; expiresAt: number | null }>()
  private readonly _sets = new Map<string, Set<string>>()
  /** Sorted sets, member -> score. Ordering is applied on read, as Redis does. */
  private readonly _zsets = new Map<string, Map<string, number>>()
  private readonly _channels = new Map<string, Set<(channel: string, message: string) => void | Promise<void>>>()

  private _maybeExpire(key: string): void {
    const entry = this._data.get(key)
    if (entry && entry.expiresAt !== null && entry.expiresAt < Date.now()) {
      this._data.delete(key)
    }
  }

  /** `RedisLike.get` substitute. Returns null on miss or after TTL elapsed. */
  async get(key: string): Promise<string | null> {
    this._maybeExpire(key)
    return this._data.get(key)?.value ?? null
  }

  /** `RedisLike.set` with optional `EX`/`NX`. Returns null when the NX condition fails. */
  async set(key: string, value: string, opts: { ex?: number; nx?: boolean } = {}): Promise<'OK' | null> {
    this._maybeExpire(key)
    if (opts.nx && this._data.has(key)) return null
    this._data.set(key, {
      value,
      expiresAt: opts.ex !== undefined ? Date.now() + opts.ex * 1000 : null,
    })
    return 'OK'
  }

  /**
   * `RedisLike.del` variadic. Returns count of keys actually removed.
   *
   * Every type, the way real `DEL` behaves. This used to touch `_data` alone, so
   * deleting a set or a sorted set was a silent no-op - and the session store's
   * index and expiry keys are exactly those types. `runSessionStoreCompliance`
   * runs the whole contract against this class specifically to catch divergences
   * in-process, and any case asserting "the index key is gone" was passing
   * against a fake that had not removed it.
   */
  async del(...keys: string[]): Promise<number> {
    let deleted = 0
    for (const k of keys) {
      const hit = this._data.delete(k)
      const hitSet = this._sets.delete(k)
      const hitZset = this._zsets.delete(k)
      if (hit || hitSet || hitZset) deleted++
    }
    return deleted
  }

  /** `RedisLike.expire`. Returns 0 when the key does not exist. */
  async expire(key: string, seconds: number): Promise<number> {
    this._maybeExpire(key)
    const entry = this._data.get(key)
    if (!entry) return 0
    entry.expiresAt = Date.now() + seconds * 1000
    return 1
  }

  /** `RedisLike.scan`. Walks both string and set keys, since real Redis SCAN is type-agnostic. */
  async scan(cursor: string, opts: { match?: string; count?: number } = {}): Promise<[string, string[]]> {
    const all = [...new Set<string>([...this._data.keys(), ...this._sets.keys()])]
    const start = Number(cursor) || 0
    const count = opts.count ?? 100
    const matched: string[] = []
    let i = start
    for (; i < all.length && matched.length < count; i++) {
      const key = all[i]
      if (!key) continue
      this._maybeExpire(key)
      const liveString = this._data.has(key)
      const liveSet = this._sets.has(key)
      if (!liveString && !liveSet) continue
      if (opts.match && !matchGlob(key, opts.match)) continue
      matched.push(key)
    }
    const nextCursor = i >= all.length ? '0' : String(i)
    return [nextCursor, matched]
  }

  /** `RedisLike.incr` atomic increment. Creates the key at 1 when missing. */
  async incr(key: string): Promise<number> {
    this._maybeExpire(key)
    const entry = this._data.get(key)
    const cur = entry ? Number(entry.value) : 0
    const next = (Number.isFinite(cur) ? cur : 0) + 1
    this._data.set(key, {
      value: String(next),
      expiresAt: entry?.expiresAt ?? null,
    })
    return next
  }

  /** `RedisLike.sadd` variadic. Returns count of new members. */
  async sadd(key: string, ...members: string[]): Promise<number> {
    let set = this._sets.get(key)
    if (!set) {
      set = new Set()
      this._sets.set(key, set)
    }
    let added = 0
    for (const m of members) {
      if (!set.has(m)) {
        set.add(m)
        added++
      }
    }
    return added
  }

  /** `RedisLike.srem` variadic. Returns count of removed members. */
  async srem(key: string, ...members: string[]): Promise<number> {
    const set = this._sets.get(key)
    if (!set) return 0
    let removed = 0
    for (const m of members) {
      if (set.delete(m)) removed++
    }
    if (set.size === 0) this._sets.delete(key)
    return removed
  }

  /** `RedisLike.smembers`. Returns empty array when key missing. */
  async smembers(key: string): Promise<string[]> {
    return [...(this._sets.get(key) ?? [])]
  }

  /** `RedisLike.zadd`. Returns 1 when the member is new, 0 when only its score moved. */
  async zadd(key: string, score: number, member: string): Promise<number> {
    let zset = this._zsets.get(key)
    if (!zset) {
      zset = new Map()
      this._zsets.set(key, zset)
    }
    const isNew = !zset.has(member)
    zset.set(member, score)
    return isNew ? 1 : 0
  }

  /** `RedisLike.zrem` variadic. Returns count of removed members. */
  async zrem(key: string, ...members: string[]): Promise<number> {
    const zset = this._zsets.get(key)
    if (!zset) return 0
    let removed = 0
    for (const member of members) {
      if (zset.delete(member)) removed++
    }
    if (zset.size === 0) this._zsets.delete(key)
    return removed
  }

  /** `RedisLike.zrangebyscore`. Inclusive bounds, ascending by score then member. */
  async zrangebyscore(
    key: string,
    min: number | string,
    max: number | string,
    opts: { limit?: { offset: number; count: number } } = {},
  ): Promise<string[]> {
    const zset = this._zsets.get(key)
    if (!zset) return []
    const lo = bound(min, Number.NEGATIVE_INFINITY)
    const hi = bound(max, Number.POSITIVE_INFINITY)
    const hits = [...zset.entries()]
      .filter(([, score]) => score >= lo && score <= hi)
      // Redis orders by score, then lexicographically among equal scores. Tests
      // that plant several rows at one instant depend on that being stable.
      .sort(([aMember, aScore], [bMember, bScore]) => aScore - bScore || aMember.localeCompare(bMember))
      .map(([member]) => member)
    if (!opts.limit) return hits
    return hits.slice(opts.limit.offset, opts.limit.offset + opts.limit.count)
  }

  /** `RedisPubSubClient.publish` stub. Fans the payload out to every subscriber on `channel`. */
  async publish(channel: string, message: string): Promise<number> {
    const set = this._channels.get(channel)
    if (!set) return 0
    for (const handler of set) {
      void handler(channel, message)
    }
    return set.size
  }

  /** `RedisPubSubClient.subscribe` stub. Returns an async unsubscribe. */
  async subscribe(
    channel: string,
    onMessage: (channel: string, message: string) => void | Promise<void>,
  ): Promise<() => Promise<void>> {
    let set = this._channels.get(channel)
    if (!set) {
      set = new Set()
      this._channels.set(channel, set)
    }
    set.add(onMessage)
    return async () => {
      set?.delete(onMessage)
      if (set && set.size === 0) this._channels.delete(channel)
    }
  }
}

/**
 * Linear-time glob matcher for Redis MATCH semantics (`*` only). Replaces a prior
 * regex-construction approach that was both ReDoS-prone (`a*a*a*a*a*X` against a
 * near-match input) and crash-prone (unescaped `?` produced an invalid regex). This
 * two-pointer matcher is O(n*m) worst case and treats unknown characters as literals.
 */
const MATCH_GLOB_INPUT_MAX = 4096
const MATCH_GLOB_PATTERN_MAX = 256
function matchGlob(input: string, pattern: string): boolean {
  if (input.length > MATCH_GLOB_INPUT_MAX) return false
  if (pattern.length > MATCH_GLOB_PATTERN_MAX) return false
  let i = 0
  let p = 0
  let starIdx = -1
  let matchIdx = 0
  while (i < input.length) {
    if (p < pattern.length && pattern[p] === '*') {
      starIdx = p
      matchIdx = i
      p++
    } else if (p < pattern.length && pattern[p] === input[i]) {
      i++
      p++
    } else if (starIdx !== -1) {
      p = starIdx + 1
      matchIdx++
      i = matchIdx
    } else {
      return false
    }
  }
  while (p < pattern.length && pattern[p] === '*') p++
  return p === pattern.length
}

/** Factory around {@link FakeRedis}, for callers who prefer functions to `new`. */
export function fakeRedis(...args: ConstructorParameters<typeof FakeRedis>): FakeRedis {
  return new FakeRedis(...args)
}
