// -- Config factory --

// -- Memory adapter (included in root for convenience) --
export type { MemoryAdapterInit } from './adapters/memory'
export { MemoryAdapter } from './adapters/memory'
export type {
  AccessConfig,
  AccessConfigInput,
  AccessRequest,
  Adapter,
  Attributes,
  AttributeValue,
  CombiningAlgorithm,
  Condition,
  ConditionGroup,
  ConditionGroupTrace,
  ConditionLeafTrace,
  ConditionTrace,
  Decision,
  Effect,
  EngineConfig,
  EngineHooks,
  Environment,
  ExplainResult,
  ExplainSubjectInfo,
  InferAction,
  InferResource,
  InferScope,
  Operator,
  Permission,
  PermissionCheck,
  PermissionKey,
  PermissionMap,
  Policy,
  PolicyStore,
  PolicyTrace,
  Resource,
  Role,
  RoleStore,
  Rule,
  RuleTrace,
  Scalar,
  ScopedRole,
  Subject,
  SubjectStore,
  ValidationIssue,
  ValidationResult,
} from './core'
// -- Engine --
// -- Builders --
// -- Low-level (advanced usage) --
export {
  createAccessConfig,
  defineRole,
  defineRule,
  Engine,
  evalConditionGroup,
  evaluate,
  evaluateOperator,
  evaluatePolicy,
  explainEvaluation,
  matchesAction,
  matchesResource,
  matchesResourceHierarchical,
  matchesScope,
  PolicyBuilder,
  policy,
  RoleBuilder,
  RuleBuilder,
  resolve,
  resolveConditionValue,
  resolveEffectiveRoles,
  rolesToPolicy,
  validatePolicy,
  validateRoles,
  When,
  when,
} from './core'
