/**
 * NOTE THIS WHOLE FILE IS NOT REVIEWED NEITHER TRUST BY ME THE @author wildduck2
 * it's generated by AI.
 */
export namespace RedisLike {
  /**
   * Minimal Redis interface the auth adapters consume, shaped after `@upstash/redis`.
   * `ioredis`/`iovalkey` take `set` options variadically instead, so passing one
   * straight through silently drops every TTL and NX guard; wrap those with
   * `adapters/valkey` first.
   */
  export type Client = {
    /** GET key -> value | null */
    get(key: string): Promise<string | null>
    /** MGET key... -> one value per key in order, null per miss. Optional: a client without it is
     *  served by concurrent `get`s, which costs one round trip per key instead of one for all. */
    mget?(...keys: string[]): Promise<(string | null)[]>
    /**
     * EVAL script numkeys=KEYS.length KEYS ARGV -> whatever the script returns.
     * Optional: a client without it leaves `RedisSessionImpl.update` on a read-compare-write, where two
     * clients can both read, both pass the compare and both write. See that class's doc.
     */
    eval?(script: string, keys: string[], args: (string | number)[]): Promise<unknown>
    /** SET key value [EX seconds] [NX] -> 'OK' | null (null = NX failed) */
    set(key: string, value: string, opts?: { ex?: number; nx?: boolean }): Promise<'OK' | null>
    /** DEL key... -> count */
    del(...keys: string[]): Promise<number>
    /** EXPIRE key seconds -> 1 | 0 */
    expire(key: string, seconds: number): Promise<number>
    /** INCR key -> new value (creates key=1 if missing) */
    incr(key: string): Promise<number>
    /** INCRBY key n -> new value. Optional: a client without it is served by repeated `incr`. */
    incrby?(key: string, by: number): Promise<number>
    /** SADD key member... -> added count */
    sadd(key: string, ...members: string[]): Promise<number>
    /** SREM key member... -> removed count */
    srem(key: string, ...members: string[]): Promise<number>
    /** SMEMBERS key -> array of members (empty when key missing) */
    smembers(key: string): Promise<string[]>
    /** ZADD key score member -> 1 when added, 0 when an existing member was re-scored */
    zadd(key: string, score: number, member: string): Promise<number>
    /** ZREM key member... -> removed count */
    zrem(key: string, ...members: string[]): Promise<number>
    /**
     * ZRANGEBYSCORE key min max [LIMIT offset count] -> members in score order.
     * `min`/`max` accept `'-inf'` and `'+inf'`, and are inclusive.
     */
    zrangebyscore(
      key: string,
      min: number | string,
      max: number | string,
      opts?: { limit?: { offset: number; count: number } },
    ): Promise<string[]>
  }
}

/** `'-inf'` / `'+inf'` / a numeric bound -> a number, falling back for anything else. */
function bound(v: number | string, fallback: number): number {
  if (typeof v === 'number') return v
  const parsed = Number(v)
  return Number.isNaN(parsed) ? fallback : parsed
}

/**
 * In-process substitute for tests and for apps that need the adapter shape without a Redis dependency at
 * runtime. Same surface as ioredis and upstash, with TTLs enforced on read rather than by a timer.
 */
export class FakeRedis implements RedisLike.Client {
  private readonly _data = new Map<string, string>()
  /** One TTL map for all three key types. Held beside them rather than on the string entry, because
   *  `EXPIRE` applies to any key and the session index is a set while its expiry index is a sorted set. */
  private readonly _expiresAt = new Map<string, number>()
  private readonly _sets = new Map<string, Set<string>>()
  /** Sorted sets, member -> score. Ordering is applied on read, as Redis does. */
  private readonly _zsets = new Map<string, Map<string, number>>()
  private readonly _channels = new Map<string, Set<(channel: string, message: string) => void | Promise<void>>>()

  private _maybeExpire(key: string): void {
    const at = this._expiresAt.get(key)
    if (at === undefined || at >= Date.now()) return
    this._data.delete(key)
    this._sets.delete(key)
    this._zsets.delete(key)
    this._expiresAt.delete(key)
  }

  /** `null` on a miss or an elapsed TTL. */
  async get(key: string): Promise<string | null> {
    this._maybeExpire(key)
    return this._data.get(key) ?? null
  }

  /** One entry per key, in the order asked, `null` for a miss or an elapsed TTL. */
  async mget(...keys: string[]): Promise<(string | null)[]> {
    return keys.map((key) => {
      this._maybeExpire(key)
      return this._data.get(key) ?? null
    })
  }

  /** `null` when the NX condition fails. */
  async set(key: string, value: string, opts: { ex?: number; nx?: boolean } = {}): Promise<'OK' | null> {
    this._maybeExpire(key)
    if (opts.nx && this._data.has(key)) return null
    this._data.set(key, value)
    // A bare SET drops any TTL the key had, as real Redis does without KEEPTTL.
    if (opts.ex === undefined) this._expiresAt.delete(key)
    else this._expiresAt.set(key, Date.now() + opts.ex * 1000)
    return 'OK'
  }

  /** Removes from every type, the way real `DEL` behaves. Touching `_data` alone made deleting a set or a
   *  sorted set a silent no-op, and the session store's index and expiry keys are exactly those types, so
   *  `runSessionStoreCompliance` asserting "the index key is gone" passed against a fake that kept it. */
  async del(...keys: string[]): Promise<number> {
    let deleted = 0
    for (const k of keys) {
      const hit = this._data.delete(k)
      const hitSet = this._sets.delete(k)
      const hitZset = this._zsets.delete(k)
      this._expiresAt.delete(k)
      if (hit || hitSet || hitZset) deleted++
    }
    return deleted
  }

  /** `0` when the key does not exist, whatever its type. Strings only, this answered `0` for the
   *  session index and set no TTL, so the one call that bounds that set's lifetime did nothing. */
  async expire(key: string, seconds: number): Promise<number> {
    this._maybeExpire(key)
    if (!this._data.has(key) && !this._sets.has(key) && !this._zsets.has(key)) return 0
    this._expiresAt.set(key, Date.now() + seconds * 1000)
    return 1
  }

  /** Adds one, treating a missing key as zero. */
  async incr(key: string): Promise<number> {
    return this.incrby(key, 1)
  }

  /** Adds `by`, treating a missing key as zero. */
  async incrby(key: string, by: number): Promise<number> {
    this._maybeExpire(key)
    const cur = Number(this._data.get(key) ?? 0)
    const next = (Number.isFinite(cur) ? cur : 0) + by
    // The TTL map is left alone, so INCR on a key with a TTL keeps it, as real Redis does.
    this._data.set(key, String(next))
    return next
  }

  /** Adds members to a set, answering how many were not already there. */
  async sadd(key: string, ...members: string[]): Promise<number> {
    this._maybeExpire(key)
    let set = this._sets.get(key)
    if (!set) {
      set = new Set()
      this._sets.set(key, set)
    }
    let added = 0
    for (const m of members) {
      if (!set.has(m)) {
        set.add(m)
        added++
      }
    }
    return added
  }

  /** Removes members from a set, answering how many were there. */
  async srem(key: string, ...members: string[]): Promise<number> {
    this._maybeExpire(key)
    const set = this._sets.get(key)
    if (!set) return 0
    let removed = 0
    for (const m of members) {
      if (set.delete(m)) removed++
    }
    if (set.size === 0) this._sets.delete(key)
    return removed
  }

  /** Every member of a set, as a fresh array. */
  async smembers(key: string): Promise<string[]> {
    this._maybeExpire(key)
    return [...(this._sets.get(key) ?? [])]
  }

  /** Adds a member to a sorted set, or re-scores one already in it. */
  async zadd(key: string, score: number, member: string): Promise<number> {
    this._maybeExpire(key)
    let zset = this._zsets.get(key)
    if (!zset) {
      zset = new Map()
      this._zsets.set(key, zset)
    }
    const isNew = !zset.has(member)
    zset.set(member, score)
    return isNew ? 1 : 0
  }

  /** Removes members from a sorted set, answering how many were there. */
  async zrem(key: string, ...members: string[]): Promise<number> {
    this._maybeExpire(key)
    const zset = this._zsets.get(key)
    if (!zset) return 0
    let removed = 0
    for (const member of members) {
      if (zset.delete(member)) removed++
    }
    if (zset.size === 0) this._zsets.delete(key)
    return removed
  }

  /** Ascending by score, then by member. */
  async zrangebyscore(
    key: string,
    min: number | string,
    max: number | string,
    opts: { limit?: { offset: number; count: number } } = {},
  ): Promise<string[]> {
    this._maybeExpire(key)
    const zset = this._zsets.get(key)
    if (!zset) return []
    const lo = bound(min, Number.NEGATIVE_INFINITY)
    const hi = bound(max, Number.POSITIVE_INFINITY)
    const hits = [...zset.entries()]
      .filter(([, score]) => score >= lo && score <= hi)
      // Redis orders by score, then lexicographically among equal scores; tests planting several rows at
      // one instant depend on that being stable.
      .sort(([aMember, aScore], [bMember, bScore]) => aScore - bScore || aMember.localeCompare(bMember))
      .map(([member]) => member)
    if (!opts.limit) return hits
    return hits.slice(opts.limit.offset, opts.limit.offset + opts.limit.count)
  }

  /** Fans the payload out to every subscriber on `channel`. */
  async publish(channel: string, message: string): Promise<number> {
    const set = this._channels.get(channel)
    if (!set) return 0
    for (const handler of set) {
      void handler(channel, message)
    }
    return set.size
  }

  /** Answers an async unsubscribe. */
  async subscribe(
    channel: string,
    onMessage: (channel: string, message: string) => void | Promise<void>,
  ): Promise<() => Promise<void>> {
    let set = this._channels.get(channel)
    if (!set) {
      set = new Set()
      this._channels.set(channel, set)
    }
    set.add(onMessage)
    return async () => {
      set?.delete(onMessage)
      if (set && set.size === 0) this._channels.delete(channel)
    }
  }
}

/** In-process fake implementing {@link RedisLike.Client}, for tests. */
export function fakeRedis(...args: ConstructorParameters<typeof FakeRedis>): FakeRedis {
  return new FakeRedis(...args)
}
