export { AuthError, asAuthError, rethrowAuthError, throwAuthError } from './errors'
export { AUTH_ERRORS, detail } from './errors.codes'
export { type SqlFault, STORE_RAISES, sqlError } from './errors.drivers'
export { declares, type ErrorMap, errorMap, GENERIC, type RangeOf } from './errors.map'
export { isSecretKey, redactSecrets } from './errors.scrub'
export type { Envelope } from './errors.types'
