export { AuthError, asAuthError, rethrowAuthError, throwAuthError } from './errors'
export { AUTH_ERRORS, type Carries, detail, type MetaOf } from './errors.codes'
export { declares, type ErrorMap, errorMap, type Failed, GENERIC, type RangeOf } from './errors.map'
export { isSecretKey, redactSecrets } from './errors.scrub'
export type { Envelope } from './errors.types'
